name: lp_utils
decription: Modules communs pour les projets

version: 1.0.1
homepage: https://github.com/devobs/flutter

environment:
  flutter: ">=3.0.1 <4.0.0"
  sdk: '>=2.17.1 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  quiver: ^3.0.0
  dio: ^4.0.0
  equatable: ^2.0.0
  synchronized: ^3.0.0

  sembast: ^3.0.0
  path: ^1.8.1
  intl: ^0.17.0
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
